In [47]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline 
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, root_mean_squared_error

In [4]:
df = pd.read_csv(r'C:\Users\DELL\Fastapi-Project\notebooks\car-details.csv')
df.sample(5)

,name,company,model,edition,year,owner,fuel,seller_type,transmission,km_driven,mileage_mpg,engine_cc,max_power_bhp,torque_nm,seats,selling_price
553,Hyundai i10 Magna 1.2 iTech SE,Hyundai,i10,Magna 1.2 iTech SE,2012,Fourth & Above,Petrol,Individual,Manual,76000,47.84,1197.0,78.90,111.70000,5.0,210000
2605,Hyundai Verna CRDi 1.6 SX Option,Hyundai,Verna,CRDi 1.6 SX Option,2017,Third,Diesel,Individual,Manual,35000,51.70,1582.0,126.20,259.87000,5.0,850000
583,Maruti Alto 800 LXI,Maruti,Alto,800 LXI,2013,First,Petrol,Individual,Manual,24000,53.44,796.0,47.30,69.00000,5.0,200000
3742,Renault Duster 85PS Diesel RxS,Renault,Duster,85PS Diesel RxS,2017,First,Diesel,Individual,Manual,50000,46.70,1461.0,83.80,200.00000,5.0,819999
2122,Maruti SX4 Zxi with Leather BSIII,Maruti,SX4,Zxi with Leather BSIII,2008,Second,Petrol,Individual,Manual,89000,36.66,1586.0,104.68,1421.96425,5.0,150000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6926 entries, 0 to 6925
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6926 non-null   object
 1   company        6926 non-null   object
 2   model          6926 non-null   object
 3   edition        6926 non-null   object
 4   year           6926 non-null   int64
 5   owner          6926 non-null   object
 6   fuel           6926 non-null   object
 7   seller_type    6926 non-null   object
 8   transmission   6926 non-null   object
 9   km_driven      6926 non-null   int64
 10  mileage_mpg    6718 non-null   float64
 11  engine_cc      6718 non-null   float64
 12  max_power_bhp  6717 non-null   float64
 13  torque_nm      6717 non-null   float64
 14  seats          6718 non-null   float64
 15  selling_price  6926 non-null   int64
dtypes: float64(5), int64(3), object(8)
memory usage: 865.9+ KB

In [10]:
df.describe()

,year,km_driven,mileage_mpg,engine_cc,max_power_bhp,torque_nm,seats,selling_price
count,6926.000000,6.926000e+03,6718.000000,6718.000000,6717.000000,6717.000000,6718.000000,6.926000e+03
mean,2013.420300,7.399568e+04,45.080782,1430.891337,87.766100,174.684585,5.434653,5.172707e+05
std,4.078286,5.835810e+04,10.693383,493.493277,31.724555,106.876249,0.984230,5.197670e+05
min,1983.000000,1.000000e+00,0.000000,624.000000,32.800000,47.071920,2.000000,2.999900e+04
25%,2011.000000,4.000000e+04,38.900000,1197.000000,67.100000,110.000000,5.000000,2.500000e+05
50%,2014.000000,7.000000e+04,45.340000,1248.000000,81.830000,160.000000,5.000000,4.000000e+05
75%,2017.000000,1.000000e+05,52.440000,1498.000000,100.000000,200.055660,5.000000,6.335000e+05
max,2020.000000,2.360457e+06,98.700000,3604.000000,400.000000,1863.263500,14.000000,1.000000e+07

In [11]:
df.shape

(6926, 16)

In [14]:
df.isnull().sum()

name               0
company            0
model              0
edition            0
year               0
owner              0
fuel               0
seller_type        0
transmission       0
km_driven          0
mileage_mpg      208
engine_cc        208
max_power_bhp    209
torque_nm        209
seats            208
selling_price      0
dtype: int64

In [15]:
df.select_dtypes(include = 'O')

,name,company,model,edition,owner,fuel,seller_type,transmission
0,Maruti Swift Dzire VDI,Maruti,Swift,Dzire VDI,First,Diesel,Individual,Manual
1,Skoda Rapid 1.5 TDI Ambition,Skoda,Rapid,1.5 TDI Ambition,Second,Diesel,Individual,Manual
2,Honda City 2017-2020 EXi,Honda,City,2017-2020 EXi,Third,Petrol,Individual,Manual
3,Hyundai i20 Sportz Diesel,Hyundai,i20,Sportz Diesel,First,Diesel,Individual,Manual
4,Maruti Swift VXI BSIII,Maruti,Swift,VXI BSIII,First,Petrol,Individual,Manual
...,...,...,...,...,...,...,...,...
6921,Maruti Wagon R VXI BS IV with ABS,Maruti,Wagon,R VXI BS IV with ABS,Second,Petrol,Individual,Manual
6922,Hyundai i20 Magna 1.4 CRDi,Hyundai,i20,Magna 1.4 CRDi,Second,Diesel,Individual,Manual
6923,Hyundai i20 Magna,Hyundai,i20,Magna,First,Petrol,Individual,Manual
6924,Hyundai Verna CRDi SX,Hyundai,Verna,CRDi SX,Fourth & Above,Diesel,Individual,Manual
6925,Maruti Swift Dzire ZDi,Maruti,Swift,Dzire ZDi,First,Diesel,Individual,Manual

In [16]:
columns = df.select_dtypes(include = 'O')

In [19]:
for col in columns: 
    print(f'columns: {col}') 
    print(f'cardinality: {df[col].nunique()}')
    print(df[col].unique)
    print(df[col].value_counts)

columns: name
cardinality: 2058
<bound method Series.unique of 0                  Maruti Swift Dzire VDI
1            Skoda Rapid 1.5 TDI Ambition
2                Honda City 2017-2020 EXi
3               Hyundai i20 Sportz Diesel
4                  Maruti Swift VXI BSIII
                      ...
6921    Maruti Wagon R VXI BS IV with ABS
6922           Hyundai i20 Magna 1.4 CRDi
6923                    Hyundai i20 Magna
6924                Hyundai Verna CRDi SX
6925               Maruti Swift Dzire ZDi
Name: name, Length: 6926, dtype: object>
<bound method IndexOpsMixin.value_counts of 0                  Maruti Swift Dzire VDI
1            Skoda Rapid 1.5 TDI Ambition
2                Honda City 2017-2020 EXi
3               Hyundai i20 Sportz Diesel
4                  Maruti Swift VXI BSIII
                      ...
6921    Maruti Wagon R VXI BS IV with ABS
6922           Hyundai i20 Magna 1.4 CRDi
6923                    Hyundai i20 Magna
6924                Hyundai Verna CRDi SX
6925               Maruti Swift Dzire ZDi
Name: name, Length: 6926, dtype: object>
columns: company
cardinality: 32
<bound method Series.unique of 0        Maruti
1         Skoda
2         Honda
3       Hyundai
4        Maruti
         ...
6921     Maruti
6922    Hyundai
6923    Hyundai
6924    Hyundai
6925     Maruti
Name: company, Length: 6926, dtype: object>
<bound method IndexOpsMixin.value_counts of 0        Maruti
1         Skoda
2         Honda
3       Hyundai
4        Maruti
         ...
6921     Maruti
6922    Hyundai
6923    Hyundai
6924    Hyundai
6925     Maruti
Name: company, Length: 6926, dtype: object>
columns: model
cardinality: 207
<bound method Series.unique of 0       Swift
1       Rapid
2        City
3         i20
4       Swift
        ...
6921    Wagon
6922      i20
6923      i20
6924    Verna
6925    Swift
Name: model, Length: 6926, dtype: object>
<bound method IndexOpsMixin.value_counts of 0       Swift
1       Rapid
2        City
3         i20
4       Swift
        ...
6921    Wagon
6922      i20
6923      i20
6924    Verna
6925    Swift
Name: model, Length: 6926, dtype: object>
columns: edition
cardinality: 1916
<bound method Series.unique of 0                  Dzire VDI
1           1.5 TDI Ambition
2              2017-2020 EXi
3              Sportz Diesel
4                  VXI BSIII
                ...
6921    R VXI BS IV with ABS
6922          Magna 1.4 CRDi
6923                   Magna
6924                 CRDi SX
6925               Dzire ZDi
Name: edition, Length: 6926, dtype: object>
<bound method IndexOpsMixin.value_counts of 0                  Dzire VDI
1           1.5 TDI Ambition
2              2017-2020 EXi
3              Sportz Diesel
4                  VXI BSIII
                ...
6921    R VXI BS IV with ABS
6922          Magna 1.4 CRDi
6923                   Magna
6924                 CRDi SX
6925               Dzire ZDi
Name: edition, Length: 6926, dtype: object>
columns: owner
cardinality: 5
<bound method Series.unique of 0                First
1               Second
2                Third
3                First
4                First
             ...
6921            Second
6922            Second
6923             First
6924    Fourth & Above
6925             First
Name: owner, Length: 6926, dtype: object>
<bound method IndexOpsMixin.value_counts of 0                First
1               Second
2                Third
3                First
4                First
             ...
6921            Second
6922            Second
6923             First
6924    Fourth & Above
6925             First
Name: owner, Length: 6926, dtype: object>
columns: fuel
cardinality: 4
<bound method Series.unique of 0       Diesel
1       Diesel
2       Petrol
3       Diesel
4       Petrol
         ...
6921    Petrol
6922    Diesel
6923    Petrol
6924    Diesel
6925    Diesel
Name: fuel, Length: 6926, dtype: object>
<bound method IndexOpsMixin.value_counts of 0       Diesel
1       Diesel
2       Petrol
3       Diesel
4       Petrol
         ...
6921    Petrol
6922    Diesel
6923    Petrol
6924    Diesel
6925    Diesel
Name: fuel, Length: 6926, dtype: object>
columns: seller_type
cardinality: 3
<bound method Series.unique of 0       Individual
1       Individual
2       Individual
3       Individual
4       Individual
           ...
6921    Individual
6922    Individual
6923    Individual
6924    Individual
6925    Individual
Name: seller_type, Length: 6926, dtype: object>
<bound method IndexOpsMixin.value_counts of 0       Individual
1       Individual
2       Individual
3       Individual
4       Individual
           ...
6921    Individual
6922    Individual
6923    Individual
6924    Individual
6925    Individual
Name: seller_type, Length: 6926, dtype: object>
columns: transmission
cardinality: 2
<bound method Series.unique of 0       Manual
1       Manual
2       Manual
3       Manual
4       Manual
         ...
6921    Manual
6922    Manual
6923    Manual
6924    Manual
6925    Manual
Name: transmission, Length: 6926, dtype: object>
<bound method IndexOpsMixin.value_counts of 0       Manual
1       Manual
2       Manual
3       Manual
4       Manual
         ...
6921    Manual
6922    Manual
6923    Manual
6924    Manual
6925    Manual
Name: transmission, Length: 6926, dtype: object>

In [20]:
df = df.drop(columns = ['name', 'model', 'edition'])

In [23]:
df.duplicated().sum()

19

In [25]:
df.drop_duplicates(inplace= True)

In [26]:
df.duplicated().sum()

0

In [28]:
X = df.drop(columns= 'selling_price') 
y = df['selling_price'] 

print(X.shape, y.shape)

(6907, 12) (6907,)

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [31]:
print(X_train.shape) 
print(X_test.shape)

(5525, 12)
(1382, 12)

In [38]:
num_cols = X_train.select_dtypes(include = 'number').columns.tolist()
cat_cols = [col for col in X_train.columns if col not in num_cols]

In [39]:
print(num_cols) 
print(cat_cols)

['year', 'km_driven', 'mileage_mpg', 'engine_cc', 'max_power_bhp', 'torque_nm', 'seats']
['company', 'owner', 'fuel', 'seller_type', 'transmission']

In [ ]:
num_pipe = Pipeline(steps = [
    ('imputer', SimpleImputer(strategy='median')), 
    ('scaler', StandardScaler()) 
])

cat_pipe = Pipeline(steps = [
    ('imputer', SimpleImputer(strategy= 'constant', fill_value= 'missing')), 
    ('one_hot_encoder', OneHotEncoder(handle_unknown= 'ignore', sparse_output= False, drop= 'first'))
]) 

preprocessor = ColumnTransformer(transformers = [
    ('num', num_pipe, num_cols), 
    ('cat', cat_pipe, cat_cols)
])

In [43]:
reg = RandomForestRegressor(
    n_estimators= 10, max_depth = 5, random_state = 42
)

rf_model = Pipeline(steps = [
    ('pre', preprocessor), 
    ('reg', reg)
])

In [45]:
rf_model.fit(X_train, y_train)

Pipeline(steps=[('pre',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['year', 'km_driven',
                                                   'mileage_mpg', 'engine_cc',
                                                   'max_power_bhp', 'torque_nm',
                                                   'seats']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('one_hot_encoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['company', 'owner', 'fuel',
                                                   'seller_type',
                                                   'transmission'])])),
                ('reg',
                 RandomForestRegressor(max_depth=5, n_estimators=10,
                                       random_state=42))])

In [51]:
y_train_pred = rf_model.predict(X_train) 
train_rmse = root_mean_squared_error(y_train, y_train_pred)
train_rmse

y_test_pred = rf_model.predict(X_test) 
test_rmse = root_mean_squared_error(y_test, y_test_pred)
test_rmse

c:\Users\DELL\LANGCHAIN_MODELS\venv\lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

173140.17242262536

In [ ]:
y